### ISSUE TITLE
Automate not added as trusted external app

### ISSUE THREAD

**Issue by Taomyn** [schwabe/ics-openvpn#1018]
# General information
1. Android Version 8.0 (EMUI 8.0.0, March 2019 update), 9.0 (April 2019 update)
2. Android Vendor/Custom ROM Huawei, Google
3. Device Honor 7x, Pixel 3
4. Version of the app (version number/play store version/self-built) 0.7.8
 
# Description of the issue

I am using Automate to start a VPN connection, and when it first starts I am prompted to trust Automate. If I disconnect then reconnect through Automate, I am asked to trust Automate each time again. When I look at the setting "Clear allowed external apps" it shows "Allowed apps: null"

**Comment by schwabe** [comment]
Could you add a step by step to reproduce this? I am not familiar with Automate

**Comment by Taomyn** [comment]
Hmmm, step by step not easy but I can attach the test flow I am using and a screenshot of the settings it uses

![Screenshot_20190326-153022](https://user-images.githubusercontent.com/4365929/55005488-5fca3e80-4fdc-11e9-8554-30531fa6ba64.jpg)

[OpenVPN for Android test.zip](https://github.com/schwabe/ics-openvpn/files/3008598/OpenVPN.for.Android.test.zip)

**Comment by schwabe** [comment]
Can you check if the problem also exist if you use the ["official" intents to control the app ](https://github.com/schwabe/ics-openvpn#controlling-from-external-apps)  instead of the shortcut Intent?

**Comment by Taomyn** [comment]
I changed the "Extras" to 
{"de.blinkt.openvpn.api.profileName": "Star-One VPN"}

And the OpenVPN app now logs "Profile specified in shortcut not found"

**Comment by schwabe** [comment]
You also need to change the activity

**Comment by Taomyn** [comment]
Oops, of course.

It now starts the VPN but as before I authorise the app but it still shows as "null"

![Screenshot_20190326-182947](https://user-images.githubusercontent.com/4365929/55019573-74ff9700-4ff5-11e9-9d08-b5739bd0aea6.jpg)

**Comment by Taomyn** [comment]
Just wanted to add that the same thing happens on my Pixel 3 so it's not specific to the Honor 7x.

It all seems to work except for this, although I can't seem to find a way for the OpenVPN app to close after it connects. It doesn't even show when Automate then disconnects which is perfect.

**Comment by schwabe** [comment]
Which dialog does it show? Does it specially show the name of Automate or just "ANY APPLICATION"?

**Comment by Taomyn** [comment]
I opens the app at the log window and remains on it after connecting until I hit the back button. Of course that's only when it hasn't already forgotten that I had already trusted Automate in which case that's on the screen waiting for approval.

**Comment by schwabe** [comment]
I mean the app approval screen does it ask for permission of ALL apps to control openvpn or does it ask for approval of just Automate?

This might also be an issue of not synchronsised between service process and ui process of the app. Can you force stop my app and see if it shows the correct list after that?

**Comment by Taomyn** [comment]
Looking at it closely it seems to be having problems getting the name of the app controlling it i.e. Automate.

![Screenshot_20190327-142006](https://user-images.githubusercontent.com/4365929/55079220-06294900-509c-11e9-8a8a-887be7779fb4.jpg)

Strange that it then repeats the request later.

**Comment by schwabe** [comment]
That is Automate's fault for calling startActivity instead of startActivityForResult. I will look into code if there is something strange in there.

**Comment by Taomyn** [comment]
Could it be the setting I have for "Action", it's set to "Main" which says it's "Start as a main entry point, does not expect to receive data" - there are main other settings, not sure which would be more appropriate.

**Comment by cybe** [comment]
> That is Automate's fault for calling startActivity instead of startActivityForResult. I will look into code if there is something strange in there.

Thanks for the hint.  There's an [equivalent block](https://llamalab.com/automate/doc/block/activity_start_result.html) in Automate for this. Using that, the name is shown correctly.

**Comment by Taomyn** [comment]
@cybe I confirm, that other block correctly passes the name and is saved, but only after I manually confirm the action with its notification. I will see about posting a report about this to the Automate developer.

**Comment by Taomyn** [comment]
I reported it here: https://groups.google.com/forum/#!topic/automate-user/MRXj-pfb5wI

**Comment by cybe** [comment]
>  but only after I manually confirm the action with its notification.

Try toggling "Show window". I'm unsure if this is a technical limitation.

**Comment by schwabe** [comment]
`startActivity` just does not report the calling app. Only `startactivitywithresult` does. This is the behaviour that Android does

**Comment by henrik-lindqvist** [comment]
[Activity.getCallingPackage()](https://developer.android.com/reference/android/app/Activity#getCallingPackage()) only works when an Activity is started using `startActivityForResult()`. Using it for authorization is not advised.

**Comment by Taomyn** [comment]
@cybe thanks,toggling "Show window" seems to prevent the notification and it goes straight to OpenVPN.

I will replace the block in my main flow with this one see how it goes for the next few days.

**Comment by schwabe** [comment]
@henrik-lindqvist Yeah. I see that it is non ideal. I just copied what Android itself used for permission in VPNService dialog in Android 4.1. But do you have any better idea that also works those simple apps like Tasker/Automate?

**Comment by henrik-lindqvist** [comment]
@schwabe There's sadly no simple solution, [android:permission](https://developer.android.com/guide/topics/manifest/activity-element.html#prmsn) is the only official way of protecting Activities. [Binder.getCallerUid()](https://developer.android.com/reference/android/os/Binder.html#getCallingUid()), used to identify "calling apps", is only reliable when used in a "bound service" call. So you'd have to create and export an AIDL service, which isn't so easily accessed by other apps. Leave it as is, force apps to use `startActivityForResult`, and reject any call where `getCallingPackage()` returns `"de.blinkt.openvpn"` or `null`.

**Comment by schwabe** [comment]
@henrik-lindqvist the proper aidl service already exists. And rejecting null apps did not work because all these tasker style apps don't seem to be able work.

android:permission with custom permission also does not work and got even more broken after a certain android and is a minefiled (https://commonsware.com/blog/2014/02/12/vulnerabilities-custom-permissions.html) and was present in earlier version (with the AIDL) but was removed later. 

So as much as I would like to implement a better solution I don't really see one.

**Comment by henrik-lindqvist** [comment]
@schwabe There's no additional security gained if you allow `null`, so may as well remove the check altogether. Custom `android:permission`s work just fine as they're used extensively by a lot of apps/APIs. Making it `android:protectionLevel="dangerous"` would require the user to grant it at run-time within the calling app, using [Activity.requestPermissions()](https://developer.android.com/reference/android/app/Activity.html#requestPermissions(java.lang.String[], int)) on Android 6+. Calling apps would of course have to include a `<uses-permission>`.

**Comment by schwabe** [comment]
@henrik-lindqvist The additional security is that you can deny null as user but still allow apps that call it with a proper name.

android:permission is horrible broken on < 6.0 so I did not bother into looking into the new permission so far. Declaring a custom permission on Android 5.0 breaks apps if apps are installed in the wrong order: https://github.com/commonsguy/cwac-security/blob/master/PERMS.md#android-50-behavior

 I don't know if that problem with install order is fixed or not with Android 6+. Even if it fixed it would be only Android+ and most of the users of the intent based API (Tasker, ...) cannot really use it.

Do you have an example of an app that really uses `android:permission` without sharing the same code signature? I am not aware of any.

**Comment by henrik-lindqvist** [comment]
@schwabe My app use custom permissions, as does/did every app using GCM, i've not had much issue with it. The mistake many do, is telling third-party apps to declare the `<permission>`, something only the host app should do! Third-party apps should only `<uses-permission>`. SuperSU, and other su apps, made this mistake with the `"android.permission.ACCESS_SUPERUSER"` permission, which they had to abandon because of it.

**Comment by schwabe** [comment]
Well on older android version you needed to declare the permission too because otherwise you were not granted the permission on install and could only get it by app removal/install host app/app reinstall. It was not really a mistake on older versions to declare it on older versions but necessary. For GCM the story is different because GCM is *always* installed before your app, so you can rely on GCM already being present and declaring the custom permission.

 But anyway, I am not seeing that `android:permission` would in my case would help in any case. The proper API with the AIDL interface is secure (albeit with a bit non standard way as it has too work for older Android versions) and for the intent API, the `android:permission` is also not helpful since the calling apps like Tasker/Automate/... etc don't implement requesting custom permission and then calling the AIDL/Intent interface in a way that I could get the calling bundle (if they would this, the current implementation would be fine). 

And yes the custom permission of this app was the same story as the super_user permission for similar/identical reasons. If custom permission would work we would do it but I frankly don't see a way to do it.

**Comment by henrik-lindqvist** [comment]
@schwabe For GCM the app declare the permission, which GMS enforce. As said, i should leave it as is, or remove the check altogether. An AIDL service, albeit fully secure, would make it a hazzle for third-party apps to use, requiring additional code.

**Comment by schwabe** [comment]
I think the original issue is fixed and the discussion went off topic after that. CLosing this issue.

**Comment by e-t-l** [comment]
> I think the original issue is fixed  

So what is the fix, to summarize? Because I'm sending the intent as written in the FAQ, I'm getting the trust dialog every time, it's asking to trust ALL APPS, and in Openvpn settings it says `Allowed apps:  ` (i.e. there's nothing there, not even "null").

So, what is the proper way to construct the intent? Note: I am sending this from a "Tasker-style app" (Macrodroid, to be specific).
