### ISSUE TITLE
No new versions on f-droid and google play

### ISSUE THREAD

**Issue by OmlineEditor** [schwabe/ics-openvpn#1144]
You have 0.7.13 versions on your site, but only v0.7.8 on f-droid and google play.
Are you not updating versions or new beta versions?
What is the problem why there are no new versions?

**Comment by schwabe** [comment]
The newer versions are still beta

**Comment by fazlerabbi37** [comment]
FYI, If you do a proper GitHub release instead of pushing the tag then you have the choice to mark them as latest, stable and pre-release aka beta. cc @schwabe

**Comment by schwabe** [comment]
@fazlerabbi37 I am not an expert on Github releases but I feel the tag is enough anyway. But this software is also not really downloaded from GitHub so releases on Github are not a big priority. For Fdroid the problem is that their build system does not support build.gradle.kts, so they have to do that manually.

**Comment by licaon-kter** [comment]
> For Fdroid the problem is that their build system does not support build.gradle.kts, so they have to do that manually.

Not true...any more: https://gitlab.com/fdroid/fdroiddata/-/commit/d812821b8daa3daaa3f2a44d5ab3e6fa0e55acd3 ;)

That being said @schwabe now F-Droid will pull any Tag as "stable", but you could Tag unstable as "vX.X.X-beta" and we can regex them to be ignored.

**Comment by schwabe** [comment]
In the past had normal vx.x tags for all releases and addtional vx.x-release tags just for fdroid, so they could pick up only stable releases. But then Fdroid changed to include also beta released and I dropped doing -release tags because there was no point in them anymore. If you want, I can start adding them again.

**Comment by licaon-kter** [comment]
Either way works, yes, as you wish.

**Comment by schwabe** [comment]
@licaon-kter It doesn't work that way around. You F-Droid guys needs to decide what you want, all version including beta or only fully released ones. As far as I understand offering both aka Google, with a option to join beta, does not exist on Fdroid.

**Comment by licaon-kter** [comment]
Yes we don't have an automated way to separate beta from stable yet to update "suggested" only for stable.

I meant that you decide how to tag, betas are different or stable are different, and we can modify the recipe to pick up only stable.

We can't decide for you. Eg. If we get all versions and then users get a crashing beta you can just shrug it and blame F-Droid for exposing users to versions that you, the uptream, did not deem stable enough. We, and I guess you, don't want that.

**Comment by jjakob** [comment]
K9 Mail does beta releases - they appear as normal releases but aren't "suggested" - you can still choose to install them by hand.

**Comment by licaon-kter** [comment]
@jjakob not really, it's those are pushed manually: https://gitlab.com/fdroid/fdroiddata/-/commits/master/metadata/com.fsck.k9.yml
