### ISSUE TITLE
A problem occurred starting process 'command 'swig''

### ISSUE THREAD

**Issue by vormz** [schwabe/ics-openvpn#1157]
Nevermind.

**Comment by Woopza** [comment]
I think this is some sort of path issue, because when I try to enter the swig cmd below manually over windows cmd, I get unable to locate file:

`Task ':main:generateOpenVPN3SwigskeletonDebug' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'swig''. Working directory: D:\StudioProjects\ics-openvpn\main Command: swig -outdir D:\StudioProjects\ics-openvpn\main\build\generated\source\ovpn3swig\skeleton\debug\net\openvpn\ovpn3 -outcurrentdir -c++ -java -package net.openvpn.ovpn3 -Isrc/main/cpp/openvpn3/client -Isrc/main/cpp/openvpn3/ -o D:\StudioProjects\ics-openvpn\main\build\generated\source\ovpn3swig\skeleton\debug\net\openvpn\ovpn3/ovpncli_wrap.cxx -oh D:\StudioProjects\ics-openvpn\main\build\generated\source\ovpn3swig\skeleton\debug\net\openvpn\ovpn3/ovpncli_wrap.h src/main/cpp/openvpn3/javacli/ovpncli.i
Task :main:generateOpenVPN3SwigskeletonDebug in main Finished
:main:generateOpenVPN3SwigskeletonDebug (Thread[Daemon worker Thread 5,5,main]) completed. Took 0.011 secs.`

**Comment by vormz** [comment]
Fixed by restarting the computer. Guess system did not take affect immediatly.
