### ISSUE TITLE
What change in API 29

### ISSUE THREAD

**Issue by mercadeoshop** [schwabe/ics-openvpn#1179]
Hi, i use a custom app of ICS Openvpn from codecanyon, but for what i see if i change the target sdk to 29 stop working on android 10 devices. Can you tell why is that or what change it?

**Comment by schwabe** [comment]
This bug tracker only deals with this app and this app has no problem with Target SDK 29.

**Comment by mehroz1** [comment]
*Comment Removed. See reason below*

Instead of band aid fixing an old version of the software using a library that you didn't built yourself, you should just use the latest version of the upstream software. As VPN software is security sensitive, there is no excuse in using old versions.

**Comment by schwabe** [comment]
You should never use the libraries from other packages, the repository includes everything to build it.

**Comment by mehroz1** [comment]
> 
> 
> You should never use the libraries from other packages, the repository includes everything to build it.

Yes you are right no arguments there.

**Comment by mercadeoshop** [comment]
> _Comment Removed. See reason below_
> 
> Instead of band aid fixing an old version of the software using a library that you didn't built yourself, you should just use the latest version of the upstream software. As VPN software is security sensitive, there is no excuse in using old versions.

Thank you very much for your help, was very helpfull, there is a way i can contact you?

**Comment by mehroz1** [comment]
@schwabe whatever you are trying to do is not right. You are removing comment instead of moderating it. Why so much secrecy? 

I was just answering the question why its failing on android and instead of making the comment compliant to your project you chose to entirely remove it. 

You are either clearly trying to hide something from public or you do not want anyone to implement to ics-openvpn except for official OpenVPN Android client or your own on playstore (both based on this repo). So what is it? What is it you are hiding from public? or you are using cheap tactics to earn some money for disclosing these issues. Either way you are hiding something.

**Comment by mehroz1** [comment]
> 
> 
> > _Comment Removed. See reason below_
> > Instead of band aid fixing an old version of the software using a library that you didn't built yourself, you should just use the latest version of the upstream software. As VPN software is security sensitive, there is no excuse in using old versions.
> 
> Thank you very much for your help, was very helpfull, there is a way i can contact you?

You can contact me on my github fork of EasyVPN.

**Comment by schwabe** [comment]
@mehroz1 I am not hiding something. I don't want to bad practice being spread on my github repository. That is why I removed that comment that promoted bad practice. And the official OpenVPN Connect is *NOT* based on this repo.

What I clearly don't want is insecure variants of my app floating around, ESPECIALLY not from people that do not respect the license and contribute nothing back.
