### ISSUE TITLE
Oculus Go or Quest Support

### ISSUE THREAD

**Issue by DaveSeidman** [schwabe/ics-openvpn#1182]
I may be opening this issue in the wrong place so forgive me. This is a feature request. We've been using the OpenVPN Connect client for Android on Oculus Go and have been successful at running some of our VR experiences over VPN which is awesome. However, the Android app was obviously not built for a VR headset and also needs to be side-loaded. I was wondering if you'd be interested in collaborating on an Oculus or Steam version of OpenVPN Connect as many of us VR developers are now isolated making it hard for us to test our apps that are intended to run over a LAN. I believe it's just the GUI that would need to rebuilding for a VR headsets controllers which we do often. The functionality of the client works already, it's just very difficult to use the App "in-headset" Thanks in advance!

**Comment by schwabe** [comment]
(schwabe/openvpn is the wrong repo for the Android app)

This is also OpenVPN for Android and not OpenVPN Connect. OpenVPN Connect is the commercial app from OpenVPN Inc.

As I don't own an Oculus Quest I cannot really test any UI for that. But any pull request adding an alternative (probably simplified) Oculus UI is not a problem for me. For SteamVR, I don't really understand the use case. It is probably easier to just use it on the connected Windows machine and also that is not android based.

Does the Quest use the TV UI or what happens if you run a "normal" app on a Quest?

Also I won't be buying a Quest since I already got "normal" VR googles.
