### ISSUE TITLE
Update 0.7.18 fails to connect to PIA server

### ISSUE THREAD

**Issue by bullionbob** [schwabe/ics-openvpn#1236]
# General information
1. Android Version 9
2. ArrowOS
3. Motorola Moto G (5) Plus (MSM8953)
4. FDroid version 0.7.18
 After updating to version 0.7.18, the client fails to connect. I downgraded to 0.7.17a and the client could connect again. Attached is the logfile.
[Open-vpn-log.txt](https://github.com/schwabe/ics-openvpn/files/5269506/Open-vpn-log.txt)

**Comment by schwabe** [comment]
That looks like a log connecting to a PIA server. This is broken on PIA's side:

The server does not push '--cipher', so the client has to assume that
the server does not do any cipher negotiation. The clients then try to
use the same cipher as the server. This has been always the case since
OpenVPN 2.4. But since PIA's server says it uses BF-CBC, the client
tries to switch to that cipher and it fails generating an error. The
only difference between 2.5 and 2.4 is that OpenVPN 2.4 continued to use
the cipher that was in its config and that was basically always a broken
configuration. So in OpenVPN 2.5 we made that error abort the connection.

I don't know what patches PIA uses on their server but I have not seen
any OpenVPN server beside PIA to have this behaviour.
