### ISSUE TITLE
Bug: App Won't Reconnect Upon Reboot

### ISSUE THREAD

**Issue by 8227846265** [schwabe/ics-openvpn#1288]
# General information
1. Android Version: **Android 10**
2. Android Vendor/Custom ROM: **Google**
3. Device: **[Chromecast with Google TV](https://store.google.com/us/product/chromecast_google_tv?hl=en-US)**
4. Version of the app: **Google Play Store — 0.7.21**
 
# Description of the issue
**App Settings:**
- Default VPN: Selected
- Connect on boot: Enabled
- Everything else: Default Settings

**Scenario:**
When you restart Chromecast with Google TV (Settings > System > Restart). Upon reboot, the app won't reconnect by its own, and you have to manually connect.

**Comment by schwabe** [comment]
Under Android 10 or later you should use the always on feature from the OS instead.

**Comment by 8227846265** [comment]
Hi @schwabe - Editing the OS details on the first post, Chromecast with Google TV is running on Android TV OS 10.

I just checked the settings to see if there's a VPN settings to turn on Always On feature. Sadly, it's not available.

For reference though, when I had Mi Box S which is currently on Android TV OS 9. The app reconnects automatically upon reboot. 

Thus, it seems to be an app incompatibility with the new Chromecast with Google TV, Android TV OS 10 perhaps?

**Comment by schwabe** [comment]
Yeah the old style of connect on boot is depreacted since Android 7 or 8 that introduced the always on VPN method. Android 10 finally broke it. I am currently not intending to implement a new method for Android TV. That seems a bit too niche. Setting always on vpn might work with adb commmands or using admin app but I havn't investigated yet.

**Comment by 8227846265** [comment]
Understood. Thank you for the response.

**Comment by llima27** [comment]
@8227846265 I have exactly the same setup and had been struggling with the same problem. I'm glad I found this so at least I know what I'm up against. I'm current using my VPN provider's app but wanted to switch because OpenVPN for Android is so much cleaner and lighter. If you find a way to make it work please share? I'll continue to investigate.
