### ISSUE TITLE
Connection to OpenVPN server impossible if Orbot set as proxy, when "Always-On -> Only allow connections through VPN" is enabled.

### ISSUE THREAD

**Issue by DanielKonopka** [schwabe/ics-openvpn#1424]
When "Always-On -> Only allow connections through VPN" is ON (aka Android kill switch), it is no longer possible to establish a connection to any OpenVPN server, that has Orbot selected as its proxy in Server List tab. Looks like a mutual exclusion issue. A very important one, I think, because the way it behaves now makes it possible to use OpenVPN for Android together with Orbot _only without_ system kill switch. That defies the whole purpose for me and probably others, who want to use VPN together with TOR.

**Comment by schwabe** [comment]
Yes that is by design of the Android Always on implementation. **Only** the selected VPN app can make connections without the VPN. Theoretically you can play games with throwing sockets back and forth between OpenVPN for Android and Orbot but Orbot developers would need to implement that part. The API is already available from my App for doing that dance (https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/aidl/de/blinkt/openvpn/api/IOpenVPNAPIService.aidl#L61)
