### ISSUE TITLE
Implement caching/writing log to persistent storage

### ISSUE THREAD

**Issue by schwabe** [schwabe/ics-openvpn#340]

**Comment by AlmogBaku** [comment]
Hey, I wrote some VpnStatus listener that log to file... do you want me to send a PR?

**Comment by schwabe** [comment]
@AlmogBaku I was thinking about a solution where VpnStatus caches its log to disc and automatically reloads them after a crash (and inserting a note that the log has been loaded from a cache)

Also for bigger contribution I probably need a signed CLA to keep my rights to relicense the source code.

**Comment by AlmogBaku** [comment]
Hey,
1. Where should I sign :)
2. The listener I have is logging it to a file.. the thing is the GC removing the listener.. so I had to add it the listener maually to the VpnStatus class.

**Comment by AlmogBaku** [comment]
Update:
1. Currently I have a solution which requires writing to storage permission
1. However, this implementation is a bit problematic since exposing the file to the user is not safe, and required extra permission
1. My team is working on a solution, but it will require to expose `VpnStatus` to `Context`. Do you have an input about it? will you accept a PR that shared the `Context` with `VpnStatus`?

**Comment by schwabe** [comment]
I implemented a bit different idea that caches the log in the background and uses a separate Thread for reading/writing the log cache.

**Comment by AlmogBaku** [comment]
lookin' good!
