### ISSUE TITLE
JNI glue links to libcrypto.so as a shared library

### ISSUE THREAD

**Issue by kruton** [schwabe/ics-openvpn#343]
The JNI glue links against an **_ABI unstable**_ `libcrypto.so`. This should either be statically linked with the JNI glue library or a differently-named version should be included (e.g., don't use the filename `libcrypto.so` because it conflicts with the platform).

Unfortunately, the resulting binary has been copied to many projects which will now most likely break.

**Comment by schwabe** [comment]
I do not worry to much about the other project since most of them violate the GPL anyway. The other projects that I am aware of that do not violate the GPL build the binaries themselves.

The idea behind the JNI glue stuff that it should link against the system openssl library since it directly uses a pointer from the system library for the Android keychain workaround on 4.1. I have not checked if it really links against the system library or my own libcrypto library.

I am not sure what the best action here is. I would guess I should rename my own libcrypto/libopenssl and move the keychain workaround to a libkeychainworkaround41.so that is only loaded on 4.1 and still links against libopenssl/libcrypto from the system?

**Comment by kruton** [comment]
Yes, I'd separate out the 4.1 code. Right now it prevents anything using libopvpnutil.so from working on the [Android M preview release](https://developer.android.com/preview/index.html).
