### ISSUE TITLE
open vpn disconnected when I lock my phone

### ISSUE THREAD

**Issue by hafidb** [schwabe/ics-openvpn#363]
shows not connected whenever I lock my phone in the log shows Process exited with exit value 9. it does not happen in my friend phone

I use zenfone 5 and my friend use zenfone 4

**Comment by schwabe** [comment]
exit value 9 means the openvpn process crashed. Can you use this version http://plai.de/android/ics-openvpn-0.6.31pre-min-mtu-1280.apk? That should give you the option to send a crash dump on process exit. That way I can see why openvpn is crashing.

**Comment by hafidb** [comment]
okay, I will try the app

**Comment by hafidb** [comment]
where is the option to send crash dump? I can' t find it

**Comment by schwabe** [comment]
After the app crashes there should be a log messages that the app crashed and that a log is generated. After that the option to send the dump is a new tab in the main window.

But since singal 9 is "SIGKILL" and exit vlaue 9 could also mean signal 9 there is the possibility that the crash dumps does not work. Then the only way to debug the problem is use the adb logcat from a computer and see if something of interest appear in that log.

**Comment by hafidb** [comment]
nope, there is no log message

**Comment by hafidb** [comment]
how to use the logcat?

**Comment by schwabe** [comment]
You need install the developer tools on a pc. (There are tutorial how to do that).

I know that this cumbersome for non developer but it is unfortunately the only way left I can think of at the moment.

**Comment by hafidb** [comment]
I will try
