### ISSUE TITLE
Cannot access internal storage/external storage

### ISSUE THREAD

**Issue by jabatrox** [schwabe/ics-openvpn#414]
Hi,

I have a BlackBerry Z10, in which, as you may know, it's possible to run Android apps, such as Google Maps, Youtube, file managers,... Open VPN for Android works as well.. except for one point: through the app, I can't access folders like downloads, documents, pictures, videos,... on internal nor on external storage, so I can't load my own config files and keys. It displays a message saying "Can't read the folder". It seems that the app has no permission to access these folder. However, as I said, file managers works perfectly, they show no error when accessing them or reading/writing on them.

By checking the permissions that both file manager and Open VPN have (both through BlackBerry and Android system settings), I've seen that, while file manager ask permission to "modify or delete content from the SD card", Open VPN doesn't ask for it. So I think this is the problem, the Open VPN doesn't have permission for accessing it.

Would it be possible for you to fix this by adding this extra permission to the app?

**Comment by schwabe** [comment]
I am quite sceptical that OpenVPN for Android actually works. Did you try to manually setup a VPN connection and actually connect to a VPN? Otherwise selecting/not selecting a file does not matter.

**Comment by SuperBuker** [comment]
It is not possible to manually setup the client without loading at least the ca.key.
I asked to @jabatrox which file manager apps worked on BB correctly and I discovered that all of them had in their AndroidManifest.xml <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/> instead of <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />.
I built an apk with that modification and now the file manager works and @jabatrox can load the files (.ovpn, .key, etc.) but that apk lacks all the opvn libraries. I'm sorry it's the first time I deal with gradle and ndk. :(
Apparently the @jabatrox issue is due to a wrong BB implementation of Android permissions.
 Would it be possible for you, @schwabe, to compile a sample of the app with WRITE_EXTERNAL_STORAGE on the AndroidManifest.xml?

**Comment by schwabe** [comment]
http://plai.de/android/ics-openvpn-0.6.44_sdcard_write.apk

**Comment by jabatrox** [comment]
Hi,

Thank you very much for the apk you generated. Thanks to it, I could load the files from the SD card and try to connect to the VPN. Unfortunately, I couldn't make it work, and by surfing the web with my friend @SuperBuker, I discovered that BlackBerry hasn't implemented yet the VPN's Android API in the Android emulator that is in the system:
http://developer.blackberry.com/android/apisupport/unsupported_api_jellybean_software.html

As BlackBerry keeps adding a few new Android functions in each new version o BB OS, I'll keep your permission's modified app to try it with the next OS versions.

Thank you very much again for your help, you're doing a great job with the app.
