### ISSUE TITLE
Feature Request: app blocking

### ISSUE THREAD

**Issue by autumna** [schwabe/ics-openvpn#418]
Right now the current functionality only gives the option of apps using the vpn connection or using the default connection. It would be great if there was an option to completely block the app off the internet while the connection is active. 

There are tools that uses the android vpn feature to block apps locally such as [this](https://play.google.com/store/apps/details?id=com.netspark.firewall) but it is impossible to use them together with openvpn, since android allows one connection at a time. With the added feature the user would be able to do the both. It would be very useful for anyone who doesn't have the option to root their phone.

**Comment by schwabe** [comment]
Yes. That is certainly possible. But do not except to see an implementation in OpenVPN for Android from me anytime soon. 

A firewall app could also work together with ics-openvpn to split firewall/vpn into two different apps. That requires some tricks with ParcelFileDescriptor but should be manageable.

Unfortunately the product that you linked is also closed source so implementing that feature with that app would require cooperation from their app

**Comment by AlmogBaku** [comment]
@schwabe is there a way to detect which app the packets came from in the descriptor?

**Comment by schwabe** [comment]
@AlmogBaku I really have not looked into that. I know that is some files in proc that are xt_uid or something similar that Android itself uses. They are primarily used for quota but I think you may be able to extract the information from that files.

**Comment by RoxKilly** [comment]
> Yes. That is certainly possible. But do not except to see an implementation in OpenVPN for Android from me anytime soon. **-schwabe**

Could you please elaborate on why you wouldn't want to do it?  Is it for technical reasons, or do you feel that a VPN app should limit itself to VPN duties and not perform any firewalling?

I have the same use case as the OP.

**Comment by schwabe** [comment]
@RoxKilly none that actually. More lack of interest in writing a firewall application. :) For all most own VPN uses I administrate the VPN server or trust the VPN server admin enough to trust in the firewall of that server. So for a spare time project my motivation is pretty small. 

A simple packet is easy to implement and OpenVPN even has one implemented for IPv4 (very hidden feature ...). Even a small stateful filter might be doable. The bigger problem is that a good Android implementation would also need a good UI component.

Ideally I would like to have that as a plugin or addon or something else that is reuseable even without OpenVPN for Android. Sadly, I haven't found any work that could be resued.

**Comment by takieszti91** [comment]
There is an open source app with this function: https://github.com/M66B/NetGuard

**Comment by RoxKilly** [comment]
@suliemail  Thanks for the pointer. That tool has the same drawback as the one I currently use: because it relies on Android's VPN API, it is not possible to use that tool and also use a VPN, so users are forced to choose. I am looking for a tool that allows me to control which apps have access to the internet, and that allows me to use a VPN, all without root access.

From the [FAQ](https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ2):

> Q: (2) Can I use another VPN application while using NetGuard?
> 
> A If the VPN application is using the VPN service, then no, because NetGuard needs to use this service. Android allows only one application at a time to use this service.

**Comment by takieszti91** [comment]
@RoxKilly Yes, I know. But it is open source and that's why it can help to implement this feature in OpenVPN for Android app.

**Comment by autumna** [comment]
it is amazing to see that this is actually happening.

**Comment by licaon-kter** [comment]
What's the status of this? @M66B said it's done on his side.

**Comment by schwabe** [comment]
@licaon-kter lack of time and it is not as easy as it sounds. The wrok @M66B did is a proof of concept code, so for a full working solution there is more work to be done.

**Comment by RoxKilly** [comment]
Please consider making time for this. Those of us without root are stuck in a catch 22. It really sucks to be unable to use a VPN because we use a Firewall to control over which apps get internet access and which servers apps get to interact with. On the flip side, it's agonizing to give up the firewall and all control over what our apps do online because we want to use a VPN to protect our communications.

The situation is only getting more dire because Android is doing away with even asking for internet permissions. [All apps can access the internet by default](http://www.androidpolice.com/2015/06/06/android-m-will-never-ask-users-for-permission-to-use-the-internet-and-thats-probably-okay/).

**Comment by M66B** [comment]
About openVPN/NetGuard integration:
http://forum.xda-developers.com/showpost.php?p=67952398&postcount=3122

**Comment by developer1011** [comment]
Can @M66B @schwabe please throw some light and provide a block diagram on how to have the netguard made work with a remote vpn connection using ics-openvpn. Any guidance on this would be much appreciated.

**Comment by developer1011** [comment]
@schwabe we remember you had added a very useful comment in linked netguard issue (which is unfortunately removed by M66B). Your comment explained the logical flow using arrows ->
Could you please reshare your comment here about the logical flow of integrating ics-openvpn with netguard. Thanks in advance.

**Comment by schwabe** [comment]
@developer1011 If it is deleted then it is probably gone.

**Comment by developer1011** [comment]
@schwabe could you please add the logical flow here. I am trying to integrate netguard with ics-openvpn. But ics-openvpn has it's own daemon thread and I am not getting how to route the packets first to blocker (netguard's per address blocking logic built into OpenVPNService) and then to remote vpn server

**Comment by mvglasow** [comment]
You might want to take a look at [orWall](https://f-droid.org/repository/browse/?fdid=org.ethack.orwall), which does something similar – it forces selected apps to connect through Tor rather than directly. According to the description, this is implemented using iptables and the app's user ID (each app has its own user ID). Requires root, though.

**Comment by developer1011** [comment]
@mvglasow Thanks for your inputs. Much appreciated.

Looked at the link you shared. orWall has limitations
1. orWall requires root
2. init-script works only on Android <= 4.4.x
3. Conflict: all other firewall application such as AFWall, DroidWall, etc

**Comment by licaon-kter** [comment]
Did you ask @M66B if he still has the branch somewhere?

**Comment by developer1011** [comment]
@licaon-kter some time back I had asked M66B about the tree code which was there for some time and then it was removed. Unfortunately the code does not exist anymore and M66B's suggestion was to use SOCKS5 protocol. I'm new to SOCKS5 proxy and currently do not know how to use it to handover ParcelFileDescriptor from ServiceSinkhole to OpenVPNService. Thanks for asking.

Here is a broken link that I had book marked. It now takes to 404
https://github.com/M66B/NetGuard/tree/openvpn

**Comment by schwabe** [comment]
socks5 will not work as socks5 will not work for openvpn. OpenVPN would need a tcp/ip implementation to work with socks5.

you need to do a ParcelDescriptor.createSocketPair in either server and then hand that over via AIDL or Intent to the other server. OpenVPN will then use that instead of tun. And NetGuard would have to forward these packets coming from that pipe pair to the tun device, and redirect packets coming from the tun device to that socket pair.

@M66B implementation was incomplete as it handled only one direction of that if I remember correctly. 

On my devices NetGaurd service also did break openvpn on every net change since it requested VPnService and did not use it (revoking the permission of OpenVPN by doing that). 

@developer1011 I have a copy of that branch here: https://github.com/schwabe/NetGuard/tree/openvpn

Main problem I encountered is that the proxy service that should be used also uses SinkeHoleService.java which turn opens tuns but only proxies one direction of the needed two. 

https://github.com/schwabe/NetGuard/blob/openvpn/app/src/main/java/eu/faircode/netguard/ServiceProxy.java

I was busy with other personal things beginning of the year and the refactoring needed to get that stuff  to that was more than I intially anticipated and when I finally was looking into that @M66B had abondend the project so I also did not persue that.

The cleanest way from OpenVPN would be to have an AIDL interface in the other app that minics tunbuild and also has protect so that OpenVPN for Android would just use that interface instead of the normal interface.

**Comment by shooftie** [comment]
I got the gist of what was being said so far but admit that I have less understanding of the detail.

I'd like to make my case for implementing this feature though. I travel a lot and therefore use a VPN because I'm regularly on public WiFi. Usually I will only ever want my browser or my email client to be connected because bandwidth is often precious. Having been stuck on some cesspool connections that seem to be drip-feeding packets through a pinhole, I am caught between a secure connection and one that is optimising what little bandwidth I have.

I'll stick with OpenVPN for Android regardless but this feature would be something to pay for.

Thanks for your work on this @schwabe.

**Comment by Sniper001** [comment]
@schwabe. I solved the problem with ParcelDescriptor.createSocketPair，thank you!

**Comment by schwabe** [comment]
@Sniper001 if you have something that improves my side, please share.

**Comment by Sniper001** [comment]
@schwabe.Actually nothing improve on your side,what i have done is just to share ParcelDescriptor between android vpn based apps, such as firewall app and openvpn.

**Comment by itspull** [comment]
@Sniper001 how did you >share ParcelDescriptor between android vpn based apps, such as firewall app and openvpn. in common terms?

Your description of 'solved the problem' is not understood to us 'dummies'. So, speak down to 'us'. What did you do, exactly?

**Comment by itspull** [comment]
@Sniper001 how did you > "share ParcelDescriptor between android vpn based apps, such as firewall app and openvpn." in common terms?

Your description of 'I solved the problem' is not understood to us 'dummies'. So, speak down to 'us'. What did you do, exactly, step by step?

**Comment by ghost** [comment]
@Sniper001 how did you > "share ParcelDescriptor between android vpn based apps, such as firewall app and openvpn." in common terms?

Your description of > 'I solved the problem' is not understood to us 'dummies'. So, speak 'down' to us. What did you do, exactly? Can you provide step-by-step instructions?

**Comment by AdKiller** [comment]
> 
> 
> Yes. That is certainly possible. But do not except to see an implementation in OpenVPN for Android from me anytime soon.
> 
> A firewall app could also work together with ics-openvpn to split firewall/vpn into two different apps. That requires some tricks with ParcelFileDescriptor but should be manageable.
> 
> Unfortunately the product that you linked is also closed source so implementing that feature with that app would require cooperation from their app

https://github.com/M66B/NetGuard is open source and does the application blocking & content filtering beautifully by using a local VPN on Android.  It would be amazing if you could have application blocking option while using an actual VPN service.

**Comment by schwabe** [comment]
@AdKiller see the history here for NetGuard

**Comment by AdKiller** [comment]
> 
> 
> @AdKiller see the history here for NetGuard

@schwabe most of the stuff that is discussed here goes above my head... so the conclusion is that this feature is not going to be implemented, correct?

**Comment by schwabe** [comment]
Short story: There was an attempt. I was too slow in implementing my side because I was busy with other stuff at that time, which I think upset the Netguard developer, so he delete all the WIP stuff and after that I did not try to attempt it again.

**Comment by AdKiller** [comment]
> 
> 
> Short story: There was an attempt. I was too slow in implementing my side because I was busy with other stuff at that time, which I think upset the Netguard developer, so he delete all the WIP stuff and after that I did not try to attempt it again.

Thanks for the explanation. Well that sucks. App blocking & content filtering in Android (especially while traveling & using a VPN service) would have been extremely useful to many. I am surprised that no VPN provider has implemented that already.

**Comment by xDragonZ** [comment]
VPN provider will only implement that when ICS-openvpn implemented that by copying the codes for free

**Comment by subhasiscgr** [comment]
> Short story: There was an attempt. I was too slow in implementing my side because I was busy with other stuff at that time, which I think upset the Netguard developer, so he delete all the WIP stuff and after that I did not try to attempt it again.

According to Marcel, he deleted your code only after you told him that you are not interested in the project anymore. 

I requilest you to set aside your differences and please resume the project. The android community really needs this feature. I wish I could contribute to this in person, but there is not much I can do right now.
