### ISSUE TITLE
CELLULAR  Signal Crash

### ISSUE THREAD

**Issue by biripada** [schwabe/ics-openvpn#434]
When ever my mobile data connection become bad VPN reconnects ..But at the same time 3G CELLULAR ICON Vanish from the top bar . But if  I do not use VPN and network goes bad but  it does not vanish .

I found in some  forums that VPN crashing Radio/Cellular signal when Network reset . It is only happening in Huawei LOLLIPOP mobile ..Other mobiles are okay..for those When signal strength very poor VPN just reconnects But '3G Data UP DOWN arrow ICON' still stay there.

Any Idea will be appreciate... how to know the  root cause. thank you

**Comment by schwabe** [comment]
That happens on a lot of Android 4.4 devices and I have no idea what hte cause of this is. It even made it to the FAQ. Sorry, I have knew what causes that, I would look into a workaround.

**Comment by schwabe** [comment]
Just a shot in the dark: You might try to use mssfix with a low value like 1300 and see if that changes anything.

**Comment by natsihitt** [comment]
I have same issue

**Comment by schwabe** [comment]
No response

**Comment by sevenrock** [comment]
Maybe I have a hint what happened here. Using a VPN tunnel over a mobile data connection I always saw that the mobile data connection terminated itself after some time (~10-15 minutes). Since Cyanogenmod 12.1 I need to use a patch to disable the data stall detection introduced by Google using this patch

```
--- source_12.1/frameworks/opt/telephony/src/java/com/android/internal/telephony/dataconnection/DcTrackerBase.java  2015-07-05 22:36:11.671613612 +0200
+++ cm12.1/frameworks/opt/telephony/src/java/com/android/internal/telephony/dataconnection/DcTrackerBase.java   2015-07-12 15:20:57.939856779 +0200
@@ -216,7 +216,7 @@
     // Refrence counter for enabling fail fast
     protected static int sEnableFailFastRefCounter = 0;
     // True if data stall detection is enabled
-    protected volatile boolean mDataStallDetectionEnabled = true;
+    protected volatile boolean mDataStallDetectionEnabled = false;

     protected volatile boolean mFailFast = false;

@@ -998,7 +998,7 @@
                 }
                 if (mFailFast != enabled) {
                     mFailFast = enabled;
-                    mDataStallDetectionEnabled = !enabled;
+//                    mDataStallDetectionEnabled = !enabled;
                     if (mDataStallDetectionEnabled
                             && (getOverallState() == DctConstants.State.CONNECTED)
                             && (!mInVoiceCall ||
```

Currently I am using a self-compiled Cyanogenmod 13 on my Motorola xt1039 using latest git HEAD with this patch and without any terminated connections.
Last year I tried to investigate the root cause of the problem and got stuck in some kernel code which counts the traffic on the various net interfaces. This kernel code did not count tun0 so the data stall detection assumes that no data is transfered on the mobile data connection and terminates it after some time. The traffic count on the mobile data interface was zero while all traffic was counted on tun0, I do not know whether this is correct or not.
I also do not know whether this problem is specific to the kernel version 3.4.42 being used on my Motorola phone but my patch solved the problem for me.
