### ISSUE TITLE
setUnderlyingNetworks ,setProcessDefaultNetwork / bindProcessToNetwork android API behaviour in openvpn?.

### ISSUE THREAD

**Issue by NitzDKoder** [schwabe/ics-openvpn#449]
HI folks,

When 3rd party app process network setProcessDefaultNetwork set as Cellular network and wifi is connected on device,how does the openvpn app work?Does it route requests over Cellular network?

http://stackoverflow.com/questions/28272479/app-process-network-setprocessdefaultnetwork-bindprocesstonetwork-android-api

http://developer.android.com/reference/android/net/VpnService.Builder.html#setUnderlyingNetworks(android.net.Network[])

Thanks
Nithin

**Comment by schwabe** [comment]
The app will not use the VPN but directly that interface.

**Comment by NitzDKoder** [comment]
You mean app needs to set setProcessDefaultNetwork as celluar to go over cellular data and set setProcessDefaultNetwork as wifi to go over wifi hence vpn tunnel is ignored?
Is there option to tell openvpn to take prefered network? Is that feasible?
Or look 3rd party app set network and use that network in openvpn as routing interface?

**Comment by schwabe** [comment]
@NitzDKoder I haven't yet looked into implementing that for OpenVPN for Android because there was no usecase for that. And alle VPN traffic would use that interface. And speaking of the quirkyness of VPNService interface on some Android versions that might not work on all Android platforms. (Could be something like works on 5.1+ but not on Samsung).

The methods to signal that a VPN is using something else is implemented since 5.1:

http://developer.android.com/reference/android/net/VpnService.html#setUnderlyingNetworks(android.net.Network[])

and there is also a method that allows setting bypassing of the VPN to true or false:

http://developer.android.com/reference/android/net/VpnService.Builder.html#allowBypass()

**Comment by NitzDKoder** [comment]
@schwabe thanks..above api's cant be used by 3rd party right..only the vpn service provider app can isn't? Am i missing something?
As you said new vpn api changes in android api levels 21 and 22 are not quite stable(as per my testing)

**Comment by schwabe** [comment]
@NitzDKoder yeah. I can provide that api to external apps if there is some reason to do that.
