### ISSUE TITLE
Failure to read cached log items

### ISSUE THREAD

**Issue by geronimoronin** [schwabe/ics-openvpn#455]
Nach Update auf v 0.6.49 zeigt im log "could not read log item from file 0/0"
bei version 0.6.47 ist alles in ordnung.

**Comment by whyteks** [comment]
Yes, I have been seeing this, actually since 0.6.47 
Deleting the logcache.dat file removes the error, until it comes back. Sorry I don't have a better bug report. I have not yet had time to look into it.

My wild guess would be it is happening since this commit: 
https://github.com/schwabe/ics-openvpn/commit/ca1493138f98e2781b90fd14093d6b5788181bb1

Initially I observed it on only one device, but now I observe it on two. 
I'm not an android..don't know about Parcel et al.. but it anybody wants to jump in here, another wild guess is figure out what's causing verify() to fail. Find it in the VpnStatus class: https://github.com/schwabe/ics-openvpn/blob/f3e094ce28feeaa3ba057b3260a2c0f15f401ff6/main/src/main/java/de/blinkt/openvpn/core/VpnStatus.java#L374

**Comment by Nico207** [comment]
Hi,

I have the same issue with CyanogenMod 11.
If I clear the cache, error disappear until next reboot.

**Comment by schwabe** [comment]
Yes, I know about the bug, but I am still not sure what is actually causing the bug. At the moment you can ignore the messages since they do not affect the program otherwise.
