### ISSUE TITLE
Run custom script when connection up or down

### ISSUE THREAD

**Issue by rajil** [schwabe/ics-openvpn#478]
Hello,

I use a VOIP software (Zoiper) which doesnt work unless I manually change the DNS server using setprop net.dns1. I understand that Zoiper may be at fault following this [bug](https://github.com/schwabe/ics-openvpn/issues/377) report.

I would like to run a custom script when the VPN connection goes up or down like the native up/down commands in OpenVPN. Is it possible to do this with Openvpn for Android?

My phone is running Lollipop 5.1.1

Thanks

**Comment by schwabe** [comment]
Yes, OpenVPN for Android allows the up/down commands. They are automatically stripped when you import an ovpn file since in my experience almost always the scripts were not android specific. Adding up/down scripts as custom options works however. But using custom scripts is really for advanced users.

**Comment by rajil** [comment]
Thanks. I was able to add the custom up and down scripts at Advanced>Custom Options.
