### ISSUE TITLE
Missing permissions on device with restricted users

### ISSUE THREAD

**Issue by githtz** [schwabe/ics-openvpn#555]
# General information
1. Android Version: 5.0
2. Android Vendor/Custom ROM: ASUS (Rooted device)
3. Device: Asus Zenpad Z580CA
4. Version of the app (version number/play store version/self built): 0.6.57 (Google Play)
# EDIT: READ FIRST

Problem does not occur for any kind of user, but for 'restricted profiles'. This seems to be something custom made by ASUS.
# Description of the issue
## What did I do:

After configuration I started the client. The client connected to the server but then suddenly the connection got interrupted.
After I read the logs appended below I removed all other users from the android device and connected again. This time the connection was successful.
After adding another user I faced the problem again.
## My Conclusion:

If multiple users are registered for the android device the permission INTERACT_ACROSS_USERS is missing and TUN-Interface cannot be started.
## Log (excerpt)
- Failed to open the tun interface
- get package uid; Neither user 10138 nor current process has android.permission.INTERACT_ACROSS_USERS
- MANAGEMENT: CMD 'needok 'OPENTUN' cancel'
- MANAGEMENT: Client disconnected
- ERROR: Cannot open TUN
- Exiting due fatal error
- Process exited with exit value 1
- MGMT: Got unrecognized command>FATAL:ERROR: Cannot open TUN

**Comment by schwabe** [comment]
Restricted users is a standard feature. The last time I tried VPN did not work at all with restricted users. Multiple "normal" users however works (either since 5.0 or since 6.0 don't remember when that was fixed)

**Comment by mstarostik** [comment]
Just came accross this(?) issue. Device is a Fire HD with child profiles. From within the "parent profile" (device's main user), configured a VPN profile and set it as default VPN and connect on boot. Traffic originating from apps in the child profile was not routed through the VPN. To eliminate all other reasons, I tried to reproduce the whole thing on a different device with just plain multiple user profiles to the same effect: An always-on connection works only for one user profile.

I could still ping accross the VPN tunnel though and a request made with curl from within an adb shell still got routed through the VPN! Digging further, I think the issue is caused by the routing rules:

```
shell@douglas:/ $ ip rule
0:      from all lookup local 
10000:  from all fwmark 0xc0000/0xd0000 lookup 99 
11000:  from all iif tun0 lookup 97 
12000:  from all fwmark 0xc0074/0xcffff lookup 1021 
12000:  from all fwmark 0x0/0x20000 uidrange 0-99999 lookup 1021 
13000:  from all fwmark 0x10063/0x1ffff lookup 97 
13000:  from all fwmark 0x1006a/0x1ffff lookup 1007 
13000:  from all fwmark 0x10074/0x1ffff uidrange 0-0 lookup 1021 
13000:  from all fwmark 0x10074/0x1ffff uidrange 0-99999 lookup 1021 
14000:  from all oif wlan0 lookup 1007 
14000:  from all oif tun0 uidrange 0-99999 lookup 1021 
15000:  from all fwmark 0x0/0x10000 lookup 99 
16000:  from all fwmark 0x0/0x10000 lookup 98 
17000:  from all fwmark 0x0/0x10000 lookup 97 
19000:  from all fwmark 0x6a/0x1ffff lookup 1007 
21000:  from all fwmark 0x74/0x1ffff lookup 1007 
22000:  from all fwmark 0x0/0xffff lookup 1007 
23000:  from all fwmark 0x0/0xffff uidrange 0-0 lookup main 
32000:  from all unreachable

```
Table 1021 contains the VPN routes; now the problem seems to be the uidrange restriction. Apps running in a different user profile have additional digits prepended to their uid, e.g.:

```
u10_a12   28261 214   1098076 46344 ffffffff 00000000 S pl.ayground.littlepiano_freetimeunlimited
```

Does the VpnService have any control over this uid range so you could extend it to include other users? Or would there be another way around this? The device is not rooted and I intend to keep it that way...
