### ISSUE TITLE
Separation of code into library - application modules

### ISSUE THREAD

**Issue by dzolnai** [schwabe/ics-openvpn#580]
Hello,
We've been working on the integration of this repository into our [open-source VPN application](https://github.com/eduvpn/android).
What we've noticed is that the code has not been separated into separate modules for the application and the library which makes it more difficult to include in other applications (the application has to be converted to a library).
If the code were separated into two modules, where the application module contains most of the UI and activities / fragments, whereas the library module contains the VPN core with the services and utilities, it would be easier to integrate into other apps which could apply their own styling.
Is there a reason why the code has not been separated this way?
If it is because of lack of time/manpower, we might be able to help out :)

**Comment by schwabe** [comment]
The code is actually quite separated. You can take the core module and they have not too much/almost no dependencies on the UI library. 

I am very hesitant to provide a full library since there already too many applications on the Play store that violate the GPL and doing work that will make that even easier for those people is not very high on my preference list as you can imagine (just look through closed issues, there are plenty where people demand help for their broken forks).

**Comment by dzolnai** [comment]
Alright, thank you for your explanation.

**Comment by schwabe** [comment]
Thanks for understanding
