### ISSUE TITLE
Porting to boring ssl

### ISSUE THREAD

**Issue by anmol1410** [schwabe/ics-openvpn#644]
Hi,

It is working fine with the OpenSSL, but as reported by Google, OpenSSL is no more supported by Android.
Can you provide steps to change the existing application to "boring SSL" ?

Any help will be appreciated!!

**Comment by schwabe** [comment]
BoringSSL is not supported at all. The problem is Boring SSL is *not* API compatible with OpenSSL so OpenVPN itself needs to be ported to Boring SSL first. If you are looking for a different SSL library, you can use mbedTLS.

And the app uses its own OpenSSL library so Android's own SSL support is not relevant here.
