### ISSUE TITLE
Building error when adding no-asm argument to openssl.config

### ISSUE THREAD

**Issue by Moussawi90** [schwabe/ics-openvpn#729]
I cloned the last version, then I just added no-asm args to pre-existed args in openssl.config. I run the the script ./import_openssl.sh, and I changed the OPENSSL_CRYPTO_DEFINES as requested for each architecture, then the script was achieved successfully
But when I'm building using ./misc/build-native.sh I got errors at the final steps
The errors are multiple definition for 'OPENSSL_cpuid_setup' and 'CRYPTO_memcmp' and 'bn_mul_mont'

is this an openssl configuration error?
My goal is to configure openssl with no-asm, so I only added no-asm to CONFIGURE_ARGS and leaving others as they are.  

_Sent from my Lge LG-H990 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by schwabe** [comment]
Getting OpenSSL to compile is a real pain. You probably have to dig through the source codes to get all defines and what files to include and what not right. I had to this on some of the files. I spend some hours getting OpenSSL to compile with asm enabled.

I am not sure why you would want to disable asm. Using mbedtls instead of OpenSSL might be a much saner alternative here.

**Comment by Moussawi90** [comment]
Can you help me working on solving this issue?
My need for C code is to do some comparison tests

_Sent from my Lge LG-H990 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by schwabe** [comment]
You need to be more specific what you are trying to achieve.  I am not going spend multiple hours into making OpenSSL compile with no-asm just for some "comparision".
