### ISSUE TITLE
Miracast drops connection when VPN is switched on

### ISSUE THREAD

**Issue by bluezed** [schwabe/ics-openvpn#749]
# General information
1. Android Version
7.1.1

2. Android Vendor/Custom ROM
BQ

3. Device
BQ Aquaris X5 Plus

4. Version of the app (version number/play store version/self built)
Play Store 

# Description of the issue
I've just got a new TV (Hisense H50NEC5205) which supports Miracast. I've never used casting before so not sure if this is normal... It works fine without VPN but as soon as I switch the VPN on my mobile on the connection drops. 
I've set "VPN für lokale Netze umgehen" setting but that doesn't seem to make a difference.

Am I missing any other settings or is there a fundamental reason why this isn't working?

Many thanks in advance!

**Comment by schwabe** [comment]
I have no idea since I have no miracast enabled devices. You might need to exclude more networks/IPs than are automatically excluded by the bypass local networks option. But unfortenately you will have to find out yourself. Running tcpdump on the VPN server and checking if any miracast packets end up there might be helpful.

**Comment by StefanBeyer** [comment]
For future reference: I had the same issue with my Miracast receiver and resolved it by adding a route on the client (e.g. "route 192.168.49.0 255.255.255.0 192.168.49.1", my receiver's IP is 192.168.49.1). In this case you don't need to allow VPN for local networks. Also, in case you set your VPN to always-on, you need to disable blocking connections without VPN in the Android VPN settings.
