### ISSUE TITLE
GDG: SIOCGIFHWADDR(lo) failed

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#754]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version - 7.1.2
2. Android Vendor/Custom ROM - Google
3. Device - Pixel XL
4. Version of the app (version number/play store version/self built) - 0.6.73
 
# Description of the issue

I haven't been able to find any documentation that references this error:

GDG: SIOCGIFHWADDR(lo) failed
 
I am using ProtonVPN - and get this error whether I use UDP or TCP. It seems consistent whether I am connected to WiFi or 3G or 4G/LTE. The only thing I've been able to find are some incomplete forum posts about the error. I'm just curious as to what it is? What does it mean? Is my communication secure or not? Thanks,

Decoy

**Comment by schwabe** [comment]
Ignore that, it is harmless, see other closed bug report for a detailed explaination.

**Comment by ghost** [comment]
> Ignore that, it is harmless, see other closed bug report for a detailed explaination.

I was unable to find the other report. Could you link me to the description? Thanks,

Decoy

**Comment by mdiluz** [comment]
Since I just found this too - for future internet detectives:

This error comes from failing to get the hardware address of the device `lo` ie. a typical Linux device name for the LAN device. Android doesn't have this, so the error is spurious, see [here](https://sourceforge.net/p/openvpn/mailman/message/35178045/).
