### ISSUE TITLE
Which version

### ISSUE THREAD

**Issue by Rhtyme** [schwabe/ics-openvpn#787]
Firstly, thanks for such a great project ics-openvpn for Android. 
I am trying to implement GOST crypto engine in this project. I have successfully implemented GOST engine in opensslu1.0.1u version and compiled then integrated with ics-openvpn project. I tested and it works fine. But when I tried to connect to the openvpn server that supports only GOST algorithms, it doesn't connect to the server and errors are thrown related to openssl 

```
OpenSSL: error:14099044:SSL routines:SSL3_SEND_CLIENT_VERIFY:internal error
TLS_ERROR: BIO read tls_read_plaintext error
TLS Error: TLS object -> incoming plaintext read error
TLS Error: TLS handshake failed
```

It seems that Russian GOST engine was supported till openvpn 2.3.18 version, so I should use openvpn 2.3.18 version to support GOST engine. But I can't find the version in your openvpn submodule. Of course there is version that is like "2.5" but this is not corresponding with the library version in openvpn.net. I searched through nearly all tags, releases of your ics-openvpn repository, but I couldn't find the version that used openvpn 2.3.18 suitable version. So can you please tell me the right ics-openvpn version which used the openvpn library corresponding openvpn-2.3.18, so that if I successfully implement Russian GOST engine, I would send you the patches.

**Comment by schwabe** [comment]
it might be that the change of the default tls-cipher changed that you might try use tls-cipher DEFAULT

But more to the point, OpenVPN for android never had a 2.3.18 version because it always followed master. So you might find a version in the openvpn repository that is close to 2.3.18 (at least from the data) but you won't find a 2.3.18 version.

Also I am not really sure what I should do with patches for an old openvpn version and and old openssl version. The app currently uses openssl 1.1.0 and openvpn master branch and it is not going back to 2.3 and openssl 1.0.2 or the even older openssl 1.0.1 version. For OpenSSL 1.1 you probably need to look at https://github.com/gost-engine/engine

**Comment by Rhtyme** [comment]
Thanks for your quick reply, I will try to find suitable openvpn for my case  and integrate with ics-openvpn project.

**Comment by Rhtyme** [comment]
Dear Arne,

As I told You my case that I should support Russian GOST algorithms in
ics-openvpn project, can you please patch openvpn-2.3.18 version with
support GOST engine and integrated with ics-openvpn Android project?
I would share the project that uses openssl-1.0.1u  version that supports
Russian GOST engine and works fine.
Of course not for free, and would like to know how much does it cost for
you to patch openvpn-2.3.18 verison?

Sincerely, Sirojiddin.

**Comment by Rhtyme** [comment]
Arne, I need your help, how to contact you? my email is rhtyme[at]gmail.com

**Comment by schwabe** [comment]
I already replied to you
