### ISSUE TITLE
Stuck at waiting for usable network on device without WiFi or SIM

### ISSUE THREAD

**Issue by casper** [schwabe/ics-openvpn#808]
Using 0.6.72 on Xiaomi Redmi 4A stock ROM. Device has no WiFi connection nor a SIM card, just a reverse tether USB connection to my Windows PC. 

The USB tether network is up and running, and telnet from the phone to the OpenVPN server port on the PC works fine.

But OpenVPN on the phone just sits there dead in the water. Shouldn't it try to connect? 

Someone said I need to toggle either WiFi or mobile data on and then off to trigger OpenVPN operation, but I can't do neither as neither is available.

Seems like a bug somewhere. The IP interface on Android is up and running just fine, so it seems OpenVPN should just go ahead and open the connection. Is there some config variable I am missing?

**Comment by schwabe** [comment]
The app waits until the device reports that it has a working network connecetion. You can disable this by unticking the box under general settings. But I think you will then have the same problem with other app as they will also believe your device has no internet connection

**Comment by casper** [comment]
You mean "reconnect on network change"? I tried it with both checked and unchecked. Same issue. 

> But I think you will then have the same problem with other app as they will also believe your device has no internet connection

Yes that is a problem, but not for most tasks. Basic web browsing works with a tethered connection, as do many other apps. Some sync-based apps don't work, as they try to check if WiFi is available to sync. But there is an Xposed module available to get around that too, but not on this phone as it requires root :-/

Is there a location in the code I could modify to skip the check for active network, and change it to just try and connect by default always? I guess I could recompile myself a version to test it out, if the check is not too complex to modify?

**Comment by schwabe** [comment]
The option should already disable that check. But DeviceStateListener is a good starting point for that

**Comment by casper** [comment]
Ok. I got as far back as `pause`. So something must be calling `pause` to stop the connection process?

> The option should already disable that check. 

Any idea why it doesn't do that? Or is there another problem? Here's a screenshot of the log window:

![image](https://user-images.githubusercontent.com/25386/34328664-e6300b96-e8ed-11e7-9c7f-d97d65dc7b82.png)

**Comment by casper** [comment]
Scratch that. `networkStateChange` seems to be where the action is. Anrdroid `getActiveNetworkInfo` is returning `null`. A tethered connection is not "nothing", but I guess Android doesn't agree with this premise.

**Comment by casper** [comment]
Ok. If I call `mManagement.resume()` directly from `networkStateChange`, regardless of what Android says about network state, will that allow OpenVPN to run properly? I.e. let's say I just hard-code a call to `resume()` inside `networkStateChange` in this case. Would that work?

**Comment by casper** [comment]
Btw. I will pay you for whatever time you spend on this problem. I'm not a commercial developer, but I just want this fixed and I appreciate any time you spend here helping. 

I've spent about 6 hours non-stop currently, starting with installing Android Studio, having never developed for Android before, but at this point I'm stuck :( 

I can get it to run on my phone in debug mode (no clue how to sign an APK, or if it's even required to be signed. I just use the debug release). But it seems to crash, even though I'm using the same 0.6.72 version of the code as the one I downloaded from the Play Store.

This is all it shows in the log output, even at the highest debug level, and nothing else happens. 

```
03:30 built by C=US,O=Android,CN=Android Debug 0.6.72 running on Xiaomi Redmi 4A
(QC_Reference_Phone), Android 6.0.1 (MMB29M) API 23, ABI error,
(Xiaomi/rolex/rolex:6.0.1/MMB29M/V8.5.1.0.MCCMIED:user/release-keys)
```

Any idea how to fix this ABI error? Do I need to build it in release-mode and sign the APK to make it work?

It might also have to do something with the fact I had to modify the code in `Utils.java`, in order to get the file dialog to work (see #634), as it seems to crash generating the config now.

**Comment by casper** [comment]
Success!! Switched from Window to Linux, and all weird problems stopped. 

With the fix below OpenVPN connects without problems, and I can use the phone almost normally.

Reverse tethering is now possible without root, and without SIM or WiFi.

```
    public void networkStateChange(Context context) {
        NetworkInfo networkInfo = getCurrentNetworkInfo(context);
        SharedPreferences prefs = Preferences.getDefaultSharedPreferences(context);
        boolean sendusr1 = prefs.getBoolean("netchangereconnect", true);

        network = connectState.SHOULDBECONNECTED;
        lastNetwork = ConnectivityManager.TYPE_ETHERNET;
        // lastConnectedNetwork = "forced tether";

        VpnStatus.logInfo(R.string.netstatus, "force connect");
        mManagement.resume(); 

        if (true) return;
        ...
```

**Comment by eSavior** [comment]
There's a thread over on GitLab that explains how to get this working without code changes on a rooted Android device using the XPosed "Fake WiFi" module: https://gitlab.com/billhibadb/ics-openvpn/issues/336

I just posted about getting the above items configured properly allowing me to get OpenVPN connectivity going over Ethernet on my ancient HTC One M8 running Android 4.4.2.

**Comment by db8200** [comment]
Thank you Casper for sharing your 2017 Christmas success with the community! Your 5 lines of code are definitely useful, and saved me a lot of time identifying what needs to be changed to connect a non-rooted device to Internet through a computer in USB tethering mode without any SIM card or Wifi connection.

Instead of having to find different solutions to root every device and configure a reverse USB tethering connection depending on its Android version, this patched ics-openvpn allows to configure any device the same way and in a very short time.

This feature should be integrated to ics-openvpn main repository because it is a huge improvement.

Maybe there could be an option in the menu to choose between 3 behaviours:
- check if the system says that network connectivity is available (current solution)
- check if the remote openvpn server address is accessible
- disable connectivity checks (what Casper's code does)

**Comment by db8200** [comment]
Patching ics-openvpn using Casper's code has been useful for some devices, but on Android 10 or 11, ics-openvpn ended with an infinite loop with "network unreachable" even if pinging an IP address works in the shell.
I finally found that gnirehtet is a better option for connecting any non-rooted Android device through a computer via an USB cable. It also uses a VPN connection, but handles both client and server sides without having anything to configure.
The same team also developed scrcpy, which clones the phone's screen on the computer.
Since reverse USB tethering is not a primary use case for ics-openvpn, I think it's better to use gnirehtet.
