### ISSUE TITLE
App restriction version (not set) does not match expected version 1

### ISSUE THREAD

**Issue by Allineer** [schwabe/ics-openvpn#953]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version **6.0**
2. Android Vendor/Custom ROM
3. Device **DooGee X5Max**
4. Version of the app (version number/play store version/self-built) **0.7.6**
 
# Description of the issue
Quick reconnects with message in log: "App restriction version (not set) does not match expected version 1"

![photo_2018-10-16_09-00-34](https://user-images.githubusercontent.com/1168049/47004776-f693f480-d13a-11e8-9c4b-eea7bb6a4fc5.jpg)

0.7.5 works without any problems

**Comment by Yaff1e** [comment]
I'm getting the same with a freshly wiped / reinstalled phone that was working before wiping. It's fine until I use certain apps e.g Solid Explorer connecting to SMB, HP iLO or JuiceSSH.

General information
Android Version 8.1
Android Vendor LineageOS 15.1
Device OnePlus One
Version of the app 0.7.6

**Comment by jcaten** [comment]
I am having the same problem:
General Information
Android Version 8.0
Nexus 8 phone
Version of the app 0.7.6

Work good on Android 7.0 and below

**Comment by jcaten** [comment]
See this link sound like the problem I am having running on V8.1:

Starting a VpnService before the VPN app promotes itself to the foreground.

https://developer.android.com/about/versions/oreo/background

Note: IntentService is a service, and is therefore subject to the new restrictions on background services. As a result, many apps that rely on IntentService do not work properly when targeting Android 8.0 or higher. For this reason, Android Support Library 26.0.0 introduces a newJobIntentService class, which provides the same functionality as IntentService but uses jobs instead of services when running on Android 8.0 or higher.  

Any suggestions?  I'll do more reading.  Thanks

**Comment by Yaff1e** [comment]
It's not much help in getting to the cause of the problem but my Oneplus One (with LineageOS 15.1) completely died. I've replaced it with a 6T and the problem isn't there on OxygenOS. I'm not sure if it was something in LineageOS causing the issue?

**Comment by schwabe** [comment]
No. The message you are seeing is just a result of using the beta version and seeing a debug message.  The crashing etc. you are seeing are probably the lzo problem tracked in another issue.

**Comment by ghost** [comment]
Hi, which issue is that? I'm getting this error message too and the VPN disconnects and does not reconnect.

**Comment by schwabe** [comment]
@andreasmjg this message has nothing to do at all with your problme
